# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a9778b124c72e4a575b81e2309a73f32b68cd01c8608348529325ac42d3cfadee94b17e22a5de981ed9a0863102a1d8534f088e30915e904b7f74932ae29e45

test:
  secret_key_base: 41a43a877266a38fb2148f0c9cc3407302946c791db165b188db77802386b74f5dbde53a69ab7aab40ff4cf0d33151d254059029b6f3d8785873febb6506b7b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
